---
title: "Actual Statistics"
output:
  html_document:
    df_print: paged
---
# Simple Results for Border Districts

```{r}

BasicResults <- function(DataFrame, RHS, PartialLHS){ 
  list(
lm(as.formula(paste(PartialLHS[1],"~", RHS)), DataFrame),
lm( as.formula(paste(PartialLHS[2],"~", RHS)), DataFrame),
lm( as.formula(paste(PartialLHS[3],"~", RHS)), DataFrame),
lm( as.formula(paste(PartialLHS[4],"~", RHS)), DataFrame),
lm( as.formula(paste(PartialLHS[5],"~", RHS)), DataFrame)
)
}
```


Should give rough idea if it works
```{r}
library(dplyr)

LHS <- c("ELALogit", "MathLogit","ReadingLogit", "ScienceLogit", "WritingLogit")

partform <- "Eligible + NewlyTreated + Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct + as.factor(DistrictID)"

SimpleResults <- BasicResults(Master, partform, LHS )

lapply(SimpleResults, summary)
```

Lets look at the contol and treated




Now get to basic modeling with only the boarder districts.
```{r}
Master %>%
  filter(BorderDistrict == TRUE) %>%
  filter(Eligible == "NO"| EverTreated == TRUE) -> RegDiscData


RegDiscData %>%
  group_by(Eligible, Treated) %>%
  summarise(mean(ELA, na.rm = TRUE), mean(Math, na.rm = TRUE), mean(Reading, na.rm = TRUE), mean(Science, na.rm = TRUE), mean( Writing, na.rm = TRUE))

# Check for special schools

RegDiscData %>%
  select(School) %>% unique() %>% View()

RegDiscData %>%
  filter(contains(School)


# LHS <- c("ELALogit", "MathLogit","ReadingLogit", "ScienceLogit", "WritingLogit")
# 
# partform <- "Eligible + Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct "
# 
# SimpleResults <- BasicResults(RegDiscData[RegDiscData$GradeEleven > 0 ,], partform, LHS )
# 
# lapply(SimpleResults, summary)


LHS <- c("AttendanceLogit")

summary(lm(AttendanceLogit ~ Eligible + Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = RegDiscData[RegDiscData$GradeThree > 0 ,] ))

partform <- "Eligible + Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct "

SimpleResults <- BasicResults(RegDiscData[RegDiscData$GradeEight > 0 ,], partform, LHS )

lapply(SimpleResults, summary)

```


Not seeing a there there

```{r}

Master %>%
  filter(BorderDistrict == TRUE) %>%
  filter(Eligible == "YES") -> OnlyEligible 

summary(lm(AttendanceLogit ~ Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct + as.factor(DistrictID), data = OnlyEligible[OnlyEligible$GradeThree > 0 ,] ))


summary(lm(AttendanceLogit ~ Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct  + as.factor(DistrictID), data = OnlyEligible[OnlyEligible$GradeEight > 0 ,] ))


summary(lm(AttendanceLogit ~ Treated + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct  + as.factor(DistrictID), data = OnlyEligible[OnlyEligible$GradeEleven > 0 ,] ))

```

Hmmm.  What if only some kinds of interventions work.  Lets go for the broad types

```{r}

library(dplyr)

LHS <- c("ELALogit", "MathLogit","ReadingLogit", "ScienceLogit", "WritingLogit")

# Need to go back and give a indicator for each EEM type that in analogous to Treated and NewlyTreated.
# 
# 
partform <- "Eligible + FixtureMod + Boiler + Lamp + Distribution + Chiller + Insulation + Windows + Other + Maintenance + Flow + Doors + HeatRecovery + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct"

SimpleResults <- BasicResults(RegDiscData[RegDiscData$GradeThree > 0,], partform, LHS )

lapply(BasicResults(RegDiscData[RegDiscData$GradeThree > 0,], partform, LHS ), summary)

lapply(BasicResults(RegDiscData[RegDiscData$GradeEight > 0,], partform, LHS ), summary)

lapply(BasicResults(RegDiscData[RegDiscData$GradeEleven > 0,], partform, LHS ), summary)


summary(lm(AttendanceLogit ~ Eligible + FixtureMod + Boiler + Lamp + Distribution + Chiller + Insulation + Windows + Other + Maintenance + Flow + Doors + HeatRecovery + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = RegDiscData[RegDiscData$GradeThree > 0 ,] ))


summary(lm(AttendanceLogit ~ Eligible + FixtureMod + Boiler + Lamp + Distribution + Chiller + Insulation + Windows + Other + Maintenance + Flow + Doors + HeatRecovery + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = RegDiscData[RegDiscData$GradeEight > 0 ,] ))


summary(lm(AttendanceLogit ~ Eligible + FixtureMod + Boiler + Lamp + Distribution + Chiller + Insulation + Windows + Other + Maintenance + Flow + Doors + HeatRecovery + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = RegDiscData[RegDiscData$GradeEleven > 0 ,] ))


```
 Now for the parallel movement check.  No evidence that it is not
 
```{r}


TestParallel <- "EverTreated*as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct "

library(dplyr)

ParallelTestData <- RegDiscData %>%
  filter(Treated == FALSE)

lapply(BasicResults(ParallelTestData[ParallelTestData$GradeThree > 0,], TestParallel, LHS ), summary)

lapply(BasicResults(ParallelTestData[ParallelTestData$GradeEight > 0,], TestParallel, LHS ), summary)

lapply(BasicResults(ParallelTestData[ParallelTestData$GradeEleven > 0,], TestParallel, LHS ), summary)


summary(lm(AttendanceLogit ~ EverTreated*as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = ParallelTestData[ParallelTestData$GradeThree > 0 ,] ))

summary(lm(AttendanceLogit ~EverTreated*as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = ParallelTestData[ParallelTestData$GradeEight > 0 ,] ))

summary(lm(AttendanceLogit ~EverTreated*as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct, data = ParallelTestData[ParallelTestData$GradeEleven > 0 ,] ))



```
 
 
 # Now on to refinements with CEM
 
```{r}
library(cem)
library(dplyr)

RegDiscData %>%
  ungroup() %>%
  select(Eligible,
         MalePct,
         WhitePct,
         AAPct,
         HispanicPct,
         AsianPct,
         FreeLunchPct)%>%
  na.omit() -> TestCEM

mat <- cem(data = TestCEM, treatment = "Eligible", drop = c("SchoolID", "Year", "ELALogit"), keep.all = TRUE, verbose = 2, cutpoints = list(MalePct = c(0, seq(.48, .53, 6), 1), WhitePct = c(0, seq(.40, .80, 8),1), AAPct = c(0, seq(.04, .8, 8),1), HispanicPct = c(0, seq(.05, .45, 8), 1), AsianPct = c(seq(0, .2, 8), 1), FreeLunchPct = 15)
           )

table(mat$w)



#Starting CEM code

library(cem)

partform <- "Eligible + FixtureMod + Lamp + Controls + Insulation + Windows +  Doors+ Boiler + Distribution + Chiller + HeatRecovery + Flow  + Other + Maintenance + as.factor(Year) + MalePct + WhitePct + AAPct + HispanicPct + AsianPct + FreeLunchPct"

RDDCEMResults <- function(LHS, DataFrame) {
  Form <- as.formula(paste0(LHS, "~", partform))
  
  DataFrame %>%
  ungroup() %>%
  select(Eligible,
         MalePct,
         WhitePct,
         AAPct,
         HispanicPct,
         AsianPct,
         FreeLunchPct)%>%
  na.omit() -> ForCEM
  
  print(length(ForCEM))
  

  mat <- cem(data = ForCEM, treatment = "Eligible", keep.all = TRUE, verbose = 2, cutpoints = list(MalePct = c(0, seq(.48, .53, 6), 1), WhitePct = c(0, seq(.40, .80, 8),1), AAPct = c(0, seq(.04, .8, 8),1), HispanicPct = c(0, seq(.05, .45, 8), 1), AsianPct = c(seq(0, .2, 8), 1), FreeLunchPct = 15)
           )
  print(length(mat$w))
    
  lm(Form, data = DataFrame, weights = mat$w)
}


EMath <- 
  
  RDDCEMResults("MathLogit", RegDiscData[RegDiscData$GradeThree >0,] )

RegDiscData[RegDiscData$GradeThree >0,] %>% View()

Form <- as.formula(paste0(LHS, "~", partform))
attributes(terms(Form)$variables
  
  RegDiscData[RegDiscData$GradeThree >0,] %>%
  ungroup() %>%
  select(contains(LHS),
         Eligible, 
         FixtureMod,
         Lamp,
         Controls,
         Insulation,
         Windows,
         Doors,
         Boiler,
         Distribution,
         Chiller,
         HeatRecovery,
         Flow,
         Other,
         Maintenance,
         Year,
         MalePct,
         WhitePct,
         AAPct,
         HispanicPct,
         AsianPct,
         FreeLunchPct)  %>%
    na.omit() -> ForEstimate
  
  ForEstimate %>% select(Eligible,
         MalePct,
         WhitePct,
         AAPct,
         HispanicPct,
         AsianPct,
         FreeLunchPct) -> ForCEM
  
  
  mat <- cem(data = ForCEM, treatment = "Eligible", verbose = 2, cutpoints = list(MalePct = c(0, seq(.48, .53, 6), 1), WhitePct = c(0, seq(.40, .80, 8),1), AAPct = c(0, seq(.04, .8, 8),1), HispanicPct = c(0, seq(.05, .45, 8), 1), AsianPct = c(seq(0, .2, 8), 1), FreeLunchPct = 15)
           )
  print(length(mat$w))
    
summary(  lm(Form, data = ForEstimate, weights = mat$w))



```
 
 

